### ISSUE TITLE
Test on Phoenix 1.0.7.12

### ISSUE THREAD

**Issue by Kofod95** [QuickPay/oscommerce-phoenix-module#1]
English below

Jeg er ved at teste modulet her på Phoenix 1.0.7.12, og er stødt på et par ting:
-checkout_confirmation giver en fejl på linje 430 require(includes/modules/checkout/build_order_totals.php) - Det skal rettes til ...includes/system/segments/checkout/build_order_totals.php')
-Samme historie på linje 431: require(includes/modules/checkout/insert_order.php) -> includes/system/segments/...

På checkout_succes kommer følgende:
Warning: strtolower() expects parameter 1 to be string, object given in xxx/includes/functions/general.php on line 837

Warning: trim() expects parameter 1 to be string, object given in xxx/includes/functions/general.php on line 837

Notice: Undefined index: oID in xxx/includes/classes/quickpay_order.php on line 24

Warning: include(includes/modules/checkout/after.php): failed to open stream: No such file or directory in xxx/includes/modules/payment/quickpay_advanced.php on line 638

Warning: include(): Failed opening 'includes/modules/checkout/after.php' for inclusion (include_path=-) in xxx/includes/modules/payment/quickpay_advanced.php on line 638

Warning: include(includes/modules/checkout/reset.php): failed to open stream: No such file or directory in xxx/includes/modules/payment/quickpay_advanced.php on line 653

Warning: include(): Failed opening 'includes/modules/checkout/reset.php' for inclusion (-) in xxx/includes/modules/payment/quickpay_advanced.php on line 653

Warning: Cannot modify header information - headers already sent by (output started at xxx/includes/functions/general.php:837) in xxx/includes/functions/general.php on line 36

Linje 638 og 653 i includes/modules/payment/quickpay_advanced.php skal erstattes med hook-calls:  $GLOBALS['hooks']->register_pipeline('after'); (638) og  $GLOBALS['hooks']->register_pipeline('reset'); (653)

I includes/classes/quickpay_order skal $_GET['oID'] erstattes med $GLOBALS['order_id'] - det er tilfældet på linje 24 (to gange) og på linje 26.

Jeg har ikke fundet løsningen på de første to warnings - Det henviser til tep_not_null, men jeg kan ikke lige finde ud af i hvilken fil. Jeg har gået igennem dem jeg umiddelbart mistænkte uden held, men måske det er lettere, hvis man har et lidt bedre overblik over filerne.

Udover ovenstående er der en del errors i Admin, men det er mest bare Undefined Constants

Jeg ved godt den er lavet til 1.0.7.7 og ikke testet på højere, så dette er blot en 'heads-up'

_______________________________________________ENGLISH_________________________________________________

I'm currently testing this module on Phoenix 1.0.7.12 and have found a few things:

-checkout_confirmation gives an error on line 430 require(includes/modules/checkout/build_order_totals.php) - This should be corrected to ...includes/system/segments/checkout/build_order_totals.php')
-Same goes for line 431: require(includes/modules/checkout/insert_order.php) -> includes/system/segments/...

On checkout_succes we have the following:
Warning: strtolower() expects parameter 1 to be string, object given in xxx/includes/functions/general.php on line 837

Warning: trim() expects parameter 1 to be string, object given in xxx/includes/functions/general.php on line 837

Notice: Undefined index: oID in xxx/includes/classes/quickpay_order.php on line 24

Warning: include(includes/modules/checkout/after.php): failed to open stream: No such file or directory in xxx/includes/modules/payment/quickpay_advanced.php on line 638

Warning: include(): Failed opening 'includes/modules/checkout/after.php' for inclusion (include_path='-') in xxx/includes/modules/payment/quickpay_advanced.php on line 638

Warning: include(includes/modules/checkout/reset.php): failed to open stream: No such file or directory in xxx/includes/modules/payment/quickpay_advanced.php on line 653

Warning: include(): Failed opening 'includes/modules/checkout/reset.php' for inclusion (include_path='-') in xxx/includes/modules/payment/quickpay_advanced.php on line 653

Warning: Cannot modify header information - headers already sent by (output started at xxx/includes/functions/general.php:837) in xxx/includes/functions/general.php on line 36

Line 638 and 653 in includes/modules/payment/quickpay_advanced.php are to be replaced with hook-calls:  $GLOBALS['hooks']->register_pipeline('after'); (638) and $GLOBALS['hooks']->register_pipeline('reset'); (653)

In includes/classes/quickpay_order the $_GET['oID'] should be replaced with $GLOBALS['order_id'] - This is the case on line 24 (twice) and on line 26.

I have not yet found the solution on the first two warnings - It refers to the function tep_not_null, but I fail to find which call to this function in which file. I've been through the files that seemed most likely without any luck, but it might be easier for someone who has a bit of a better overview of the files
 
Aside from the above, there are quite a few errors in Admin, but they are mostly just undefined constants

I know this is made for 1.0.7.7 and not tested on later versions, so this is just to give a 'heads-up'

**Comment by Kofod95** [comment]
Fejlene i Admin skyldes autoloaderen. De løses ved at fjerne linje 19: include_once(DIR_FS_CATALOG_LANGUAGES . $language . '/modules/hooks/admin/' . basename(__FILE__)); i includes/modules/hooks/admin/orders_quickpay_payment_tab.php

The errors in Admin is due to the autoloade. They are solved by removing line 19:  include_once(DIR_FS_CATALOG_LANGUAGES . $language . '/modules/hooks/admin/' . basename(__FILE__)); in includes/modules/hooks/admin/orders_quickpay_payment_tab.php

**Comment by cosminbosutar** [comment]
Hello @Kofod95 

Thank you for mentioning this.

We tested and indeed, in 1.0.7.12 there compatibility errors.

We committed a fix for this and testes the plugin up to osCommerce Phoenix v1.0.7.15

Thanks!
Cosmin

**Comment by Kofod95** [comment]
Thank you for the update - I'll try it out, as soon as I get to it, and
will let you know, in case I find something.

Thank you, and stay safe!
Daniel

Den ons. 10. mar. 2021 kl. 16.15 skrev genuineq ***@***.***>:
